#!/bin/bash

commit_check='^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(\w+\))?!?:\s.+'

# read message to var
commit_msg=$(cat $1)

if ! [[ $commit_msg =~ $commit_check ]]; then
    echo 'Use Conventional Commits: https://conventionalcommits.org'
    exit 1
fi

exit 0
