name: Publish Release

on:
    release:
        types: [published]

jobs:
    publish:
        name: Publish to Firefox AMO
        timeout-minutes: 10
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install Deps
              run: npm ci --ignore-scripts --no-audit --progress=false

            - name: Build
              run: npm run build

            - name: Bundle
              run: npm run bundle

            #- name: Sign
            #  run:
