name: Publish

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    name: Publish to Firefox AMO
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Install
        run: bun install --frozen-lockfile

      - name: Build extension
        run: bun run build

      - name: Bundle extension
        run: bun run bundle
      
      - name: Bundle source
        run: git archive --format=zip ${{ github.event.release.tag_name }} --output .out/replace_maps_source.zip

      - name: Release
        uses: browser-actions/release-firefox-addon@latest
        with:
          addon-id: replace_maps@nobkd.github.io
          addon-path: .out/replace_maps.zip
          source-path: .out/replace_maps_source.zip
          approval-note: Follow the instructions in AMO-README.md
          release-note: ${{ github.event.release.body }}  # TODO: convert md to html, h1-6 not allowed... Currently ignoring this problem, as the field is needed for publishing
          license: MPL-2.0
          auth-api-issuer: ${{ secrets.AUTH_API_ISSUER }}
          auth-api-secret: ${{ secrets.AUTH_API_SECRET }}

      # TODO: upload signed extension to release artifacts
