name: Publish Release

on:
    workflow_dispatch:
      inputs:
        tag:
          description: 'Tag to use. Has to start with extra char like "v"'
          default: 'v'
          type: string
          required: true
    release:
        types: [created]

jobs:
    publish:
        name: Publish to Firefox AMO
        timeout-minutes: 10
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install Deps
              run: npm ci --ignore-scripts --no-audit --progress=false

            - name: Update version
              env:
                TAG: ${{ github.event.release.tag_name }}
                TAG_INPUT: ${{ inputs.tag }}
              run: |
                  ${TAG:=$TAG_INPUT}
                  npm version --no-git-tag-version ${$TAG:1}
                  sed -i -e "s/\"version\": *\"[0-9A-z.\-]*\"/\"version\": $(npm pkg get version)/gi" public/manifest.json
              # TODO: push version change to main

            #- name: Sign Firefox Extension
            #  run: npm run sign -- --api-secret ${{ secrets.FIREFOX_TOKEN }}
            # TODO: add signed addon file to release
            # TODO: push release to AMO
