name: Publish

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    name: Publish to Firefox AMO
    timeout-minutes: 10
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Load cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install
        run: npm ci

      - name: Build extension
        run: npm run build

      - name: Bundle extension
        run: npm run bundle
      
      - name: Bundle source
        run: git archive --format=zip ${{ github.event.release.tag_name }} --output out/replace_maps_source.zip

      - name: Release
        uses: browser-actions/release-firefox-addon@latest
        with:
          addon-id: replace_maps@nobkd.github.io
          addon-path: out/replace_maps.zip
          source-path: out/replace_maps_source.zip
          approval-note: Follow the instructions in AMO-README.md
          #release-note: ${{ github.event.release.body }}  # TODO: convert md to html, h1-6 not allowed...
          license: MPL-2.0
          auth-api-issuer: ${{ secrets.AUTH_API_ISSUER }}
          auth-api-secret: ${{ secrets.AUTH_API_SECRET }}

      # TODO: upload signed extension to release artifacts
